---
# all applications use these settings and services
memory: 128M
instances: 1
no-route: true
buildpack: python_buildpack
services:
   - redis-rq
   - redis-metadata
   - twitter
   - configstuff
   - logging_config
   - s3_storage
